sudo: required

language: java

# https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/9
dist: trusty

jdk:
  - openjdk8
  - openjdk11

env:
  - MAVEN_VERSION=3.6.3

script:
  - mvn clean install

cache:
  directories:
    - $HOME/.m2
notifications:
  email:
    - aviy.vai@gmail.com
